# Generated by Django 4.1.2 on 2022-10-27 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 27, 14, 25, 35, 694578, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='account.accountrecord'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='account.accountrecord'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_type',
            field=models.CharField(choices=[(1, 'deposit'), (2, 'withdrawal'), (3, 'transfer')], max_length=32),
        ),
    ]
