# Generated by Django 4.1.2 on 2022-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_auditrecord_account_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAW', 'withdraw'), ('TRANSFER', 'transfer'), ('INTEREST', 'interest')], max_length=32),
        ),
    ]
