# Generated by Django 4.1.2 on 2022-10-27 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_transactionrecord_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 14, 31, 2, 322201, tzinfo=datetime.timezone.utc)),
        ),
    ]
