# Generated by Django 4.1.2 on 2022-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_transactionrecord_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'savings'), ('SUPER_SAVINGS', 'super_savings'), ('CURRENT', 'current')], default='CURRENT', max_length=32),
        ),
    ]
