# Generated by Django 4.1.2 on 2022-10-27 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_transactionrecord_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 14, 33, 8, 670009, tzinfo=datetime.timezone.utc)),
        ),
    ]
