# Generated by Django 4.1.2 on 2022-10-27 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_transactionrecord_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 14, 37, 24, 676056, tzinfo=datetime.timezone.utc)),
        ),
    ]
