# Generated by Django 4.1.2 on 2022-10-27 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_transactionrecord_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 15, 33, 42, 732054, tzinfo=datetime.timezone.utc)),
        ),
    ]
