# Generated by Django 4.1.2 on 2022-10-27 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_transactionrecord_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
